parser: "@typescript-eslint/parser"

parserOptions:
  ecmaVersion: 6
  project: tsconfig.json

env:
  node: true
  browser: true

extends:
  - airbnb-typescript
  - airbnb/hooks
  - plugin:@typescript-eslint/recommended
  - prettier
  - react-app

plugins:
  - prettier

globals:
  "cy": true

rules:
  prettier/prettier: warn

  react/react-in-jsx-scope: 0
  react/no-unescaped-entities: 0
  react/jsx-props-no-spreading: 0
  react/require-default-props: 0
  react/no-children-prop: 0
  react-hooks/exhaustive-deps: off

  no-alert: 0
  no-console: 0
  no-nested-ternary: 0
  max-classes-per-file: 0
  class-methods-use-this: 0

  import/prefer-default-export: 0

  "@typescript-eslint/no-non-null-assertion": off
  "@typescript-eslint/no-unused-vars": ["warn", { ignoreRestSiblings: true }]
  "@typescript-eslint/no-use-before-define": 0
  "@typescript-eslint/ban-ts-comment": off
