name: Eslint tests

on: [push]

jobs:
  eslint:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v3
          with:
            node-version: 16
            cache: yarn

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run eslint
        run: yarn lint > eslint-results

      - name: Get eslint results
        uses: actions/upload-artifact@v1
        if: always()
        with:
          name: eslint-results
          path: eslint-results
